### PR TITLE
Feature/5

### PR DESCRIPTION
**Pull request by BovkunLeonid**

### CODE REVIEW

**Review by RomanIlkiv — APPROVED** [review]

**Review by RomanIlkiv — CHANGES_REQUESTED** [review]
the changes had to be made already to folder Lesson_5 in Robot_Dreams repository
not in general folder

**Comment by RomanIlkiv** [comment]
I mean move all this files to Lesson_5 folder

image

**Comment by BovkunLeonid** [comment]
Unfortunately I can't figure out how to do it. I'll wait until the Lesson_5 video is available, and then I'll do everything in a new way.

**Comment by BovkunLeonid** [comment]
Added the folder, but had to create a new repository.
https://github.com/BovkunLeonid/Robot_DreamsHomtask/pull/1

**Comment by RomanIlkiv** [comment]
> Added the folder, but had to create a new repository.
> [BovkunLeonid/Robot_DreamsHomtask#1](https://github.com/BovkunLeonid/Robot_DreamsHomtask/pull/1)

good job

**Review by RomanIlkiv — APPROVED** [review]

**Comment by BovkunLeonid** [comment]
Thank you very much

**Pull request merged**
